[phases.setup]
nixPkgs = ["nodejs_20", "openssl"]

[phases.install]
# Use npm install instead of npm ci since we're in a monorepo
cmds = ["npm install --production=false"]

[phases.build]
cmds = [
  "npx prisma generate",
  "npm run build"
]

[start]
cmd = "npx prisma migrate deploy && node dist/server.js"
